# Generated by Django 5.1.6 on 2025-03-15 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20250226_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='desctiption',
            new_name='description',
        ),
    ]
