# Generated by Django 5.1.6 on 2025-03-26 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_desctiption_product_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ['title']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['title']},
        ),
        migrations.RenameField(
            model_name='order',
            old_name='paymenent_status',
            new_name='payment_status',
        ),
    ]
